version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      # Mount volume for persistent SQLite database
      - sqlite_data:/app/instance
      # Optional: mount for logs
      - ./backend/logs:/app/logs
    environment:
      - FLASK_ENV=production
      - FLASK_APP=run.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  sqlite_data:
    driver: local 